/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          ultraDark: 'var(--color-brand-950, #001D31)',
          extraDark: 'var(--color-brand-800, #003A79)',
          dark: 'var(--color-brand-700, #0C63AA)',
          base: 'var(--color-brand-500, #008BC9)',
          light: 'var(--color-brand-300, #94CFEF)',
          extraLight: 'var(--color-brand-100, #D9F0FC)',
          50: 'var(--color-brand-50)',
          100: 'var(--color-brand-100)',
          200: 'var(--color-brand-200)',
          300: 'var(--color-brand-300)',
          400: 'var(--color-brand-400)',
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
          700: 'var(--color-brand-700)',
          800: 'var(--color-brand-800)',
          900: 'var(--color-brand-900)',
          950: 'var(--color-brand-950)',
        },
        secondary: {
          dark: 'var(--color-secondary-dark, #760A51)',
          base: 'var(--color-secondary-base, #DC189B)',
          light: 'var(--color-secondary-light, #F0A8DE)',
          extraLight: 'var(--color-secondary-lighter, #FEEBF9)',
        },
        neutral: {
          0: 'var(--color-neutral-0, #FFFFFF)',
          1: 'var(--color-neutral-1, #F7F8FA)',
          2: 'var(--color-neutral-2, #DEE1E8)',
          3: 'var(--color-neutral-3, #CACDD5)',
          4: 'var(--color-neutral-4, #969DA9)',
          5: 'var(--color-neutral-5, #677080)',
          6: 'var(--color-neutral-6, #1D2432)',
          7: 'var(--color-neutral-7, #0F1113)',
        },
        semantic: {
          error: {
            dark: 'var(--color-semantic-error-dark, #613037)',
            base: 'var(--color-semantic-error-base, #E00120)',
            light: 'var(--color-semantic-error-light, #FFACB7)',
            extraLight: 'var(--color-semantic-error-lighter, #FEE4E2)',
          },
          success: {
            dark: 'var(--color-semantic-success-dark, #267326)',
            base: 'var(--color-semantic-success-base, #3FCC33)',
            light: 'var(--color-semantic-success-light, #B8EBAD)',
            extraLight: 'var(--color-semantic-success-lighter, #EBFFE6)',
          },
          warning: {
            dark: 'var(--color-semantic-warning-dark, #DC9403)',
            base: 'var(--color-semantic-warning-base, #FFD352)',
            light: 'var(--color-semantic-warning-light, #FEF0C7)',
            extraLight: 'var(--color-semantic-warning-lighter, #FFFAEB)',
          },
          info: {
            dark: 'var(--color-semantic-info-dark, #155274)',
            base: 'var(--color-semantic-info-base, #489EEA)',
            light: 'var(--color-semantic-info-light, #B3E6F5)',
            extraLight: 'var(--color-semantic-info-lighter, #DFF8FF)',
          },
        },
        extended: {
          lavender: { dark: '#5B358A', base: '#B070F0', light: '#D9BBFF', extraLight: '#EEE0FF' },
          orange: { dark: '#96580D', base: '#E17A00', light: '#FBBE77', extraLight: '#FFE3C2' },
          oliva: { dark: '#52712A', base: '#88A94A', light: '#ADCE6D', extraLight: '#CDED90' },
          terracota: { dark: '#8B6245', base: '#AC7F5E', light: '#CFA88A', extraLight: '#E7CBB3' },
          wine: { dark: '#6E1836', base: '#A41450', light: '#CE7E8F', extraLight: '#F49EB0' },
          cherry: { dark: '#95102B', base: '#D9265C', light: '#F5A3BC' },
          clay: { dark: '#992400', base: '#FF6333', light: '#FAB49E', extraLight: '#FFE0D7' },
          wheat: { dark: '#915208', base: '#F2890D', light: '#F7C8A1' },
          aqua: { dark: '#0B645F', base: '#259E96', light: '#7ED4CD', extraLight: '#D1FBF9' },
          storm: { dark: '#16449C', base: '#0D5BF2', light: '#9EC4FA' },
          purple: { dark: '#7B387A', base: '#9F579E', light: '#C693C2', extraLight: '#EEE0FF' },
          yellowAlt: { dark: '#C2A32E', base: '#FFD744', light: '#FFE596' },
        },
        graph: {
          positive: 'var(--color-graph-positive, #004488)',
          neutral: 'var(--color-graph-neutral, #DDAA33)',
          negative: 'var(--color-graph-negative, #BB5566)',
        },
      },
      fontFamily: {
        montserrat: ['var(--font-family, Montserrat)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
