/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme$="-dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // MAPEAR Semantic UI & Layout
        bg: {
          layout: 'var(--color-backgrounds-color-bg-layout)',
          container: 'var(--color-backgrounds-color-bg-container)',
          elevated: 'var(--color-backgrounds-color-bg-elevated)',
          disabled: 'var(--color-backgrounds-color-bg-container-disabled)',
        },
        textIcon: {
          main: 'var(--color-text-icon-color-text)',
          heading: 'var(--color-text-icon-color-text-heading)',
          description: 'var(--color-text-icon-color-text-description)',
          disabled: 'var(--color-text-icon-color-text-disabled)',
          placeholder: 'var(--color-text-icon-color-text-placeholder)',
          accent: 'var(--color-text-icon-accent-color-icon-accent)',
          error: 'var(--color-text-icon-error-color-text-error)',
        },
        border: {
          DEFAULT: 'var(--color-border-color-border)',
          secondary: 'var(--color-border-color-border-secondary)',
          accent: 'var(--color-border-color-border-accent)',
          split: 'var(--color-border-color-border-split)',
          error: 'var(--color-border-error-color-border-error)',
        },
        button: {
          primary: {
            bg: 'var(--color-button-solid-primary-color-primary-bg)',
            hover: 'var(--color-button-solid-primary-color-primary-bg-hover)',
            pressed: 'var(--color-button-solid-primary-color-primary-bg-pressed)',
            text: 'var(--color-button-solid-primary-color-primary-text-button)',
          },
          secondary: {
            bg: 'var(--color-button-solid-secondary-color-secondary-bg)',
            hover: 'var(--color-button-solid-secondary-color-secondary-bg-hover)',
            pressed: 'var(--color-button-solid-secondary-color-secondary-bg-pressed)',
            text: 'var(--color-button-solid-secondary-color-secondary-text-button)',
          },
        },
        // MAPEAR Brand
        brand: {
          1: 'var(--brand-color-1)',
          2: 'var(--brand-color-2)',
          fgv: 'var(--brand-fgv)',
          active: 'var(--brand-dark-active)',
          50: 'var(--raw-color-primary-fgv-50)',
          100: 'var(--raw-color-primary-fgv-extra-light-100)',
          200: 'var(--raw-color-primary-fgv-200)',
          300: 'var(--raw-color-primary-fgv-light-300)',
          400: 'var(--raw-color-primary-fgv-400)',
          500: 'var(--raw-color-primary-fgv-base-500)',
          600: 'var(--raw-color-primary-fgv-600)',
          700: 'var(--raw-color-primary-fgv-dark-700)',
          800: 'var(--raw-color-primary-fgv-extra-dark-800)',
          900: 'var(--raw-color-primary-fgv-900)',
          950: 'var(--raw-color-primary-fgv-ultra-dark-950)',
        },
        // MAPEAR Raw Neutral Shades
        neutral: {
          0: 'var(--raw-color-neutral-0-000)',
          1: 'var(--raw-color-neutral-1-050)',
          2: 'var(--raw-color-neutral-2-200)',
          3: 'var(--raw-color-neutral-3-300)',
          4: 'var(--raw-color-neutral-4-500)',
          5: 'var(--raw-color-neutral-5-700)',
          6: 'var(--raw-color-neutral-6-900)',
          7: 'var(--raw-color-neutral-7-950)',
        },
        // MAPEAR Status & Semantic
        semantic: {
          error: {
            dark: 'var(--raw-color-semantic-warning-dark)',
            base: 'var(--raw-color-semantic-warning-base)',
            light: 'var(--raw-color-semantic-warning-light)',
            extraLight: 'var(--raw-color-semantic-warning-lighter)',
          },
          success: {
            dark: 'var(--raw-color-semantic-success-dark)',
            base: 'var(--raw-color-semantic-success-base)',
            light: 'var(--raw-color-semantic-success-light)',
            extraLight: 'var(--raw-color-semantic-success-lighter)',
          },
          caution: {
            dark: 'var(--raw-color-semantic-caution-dark)',
            base: 'var(--raw-color-semantic-caution-base)',
            light: 'var(--raw-color-semantic-caution-light)',
            extraLight: 'var(--raw-color-semantic-caution-lighter)',
          },
          info: {
            dark: 'var(--raw-color-semantic-info-dark)',
            base: 'var(--raw-color-semantic-info-base)',
            light: 'var(--raw-color-semantic-info-light)',
            extraLight: 'var(--raw-color-semantic-info-lighter)',
          },
        },
        // MAPEAR Extended Palette — Entity Chromatic System
        // Used for visual differentiation of hierarchy levels (Teste, Tarefa, Item Composto, Item)
        // and pedagogical metadata (Processo Cognitivo, Habilidade)
        extended: {
          storm: {    // 📘 Teste (Caderno)
            dark: '#16449C',
            base: '#0D5BF2',
            light: '#9EC4FA',
            extraLight: '#E8F0FE',
          },
          orange: {   // 🧩 Tarefa
            dark: '#96580D',
            base: '#E17A00',
            light: '#FBBE77',
            extraLight: '#FFE3C2',
          },
          lavender: { // 🔗 Item Composto
            dark: '#5B358A',
            base: '#B070F0',
            light: '#D9BBFF',
            extraLight: '#EEE0FF',
          },
          aqua: {     // ✏️ Item
            dark: '#0B645F',
            base: '#259E96',
            light: '#7ED4CD',
            extraLight: '#D1FBF9',
          },
          oliva: {    // 🧠 Processo Cognitivo
            dark: '#52712A',
            base: '#88A94A',
            light: '#ADCE6D',
            extraLight: '#CDED90',
          },
          cherry: {   // 🎯 Habilidade
            dark: '#95102B',
            base: '#D9265C',
            light: '#F5A3BC',
            extraLight: '#FDE8EF',
          },
          purple: {
            dark: '#7B387A',
            base: '#9F579E',
            light: '#C693C2',
            extraLight: '#EEE0FF',
          },
          wine: {
            dark: '#6E1836',
            base: '#A41450',
            light: '#CE7E8F',
            extraLight: '#F49EB0',
          },
        },
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        'x-sm': 'var(--border-radius-x-sm)',
        'xx-sm': 'var(--border-radius-xx-sm)',
        sm: 'var(--border-radius-sm)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        full: 'var(--border-radius-full)',
      },
      fontSize: {
        h0: ['var(--typography-font-size-h0)', { lineHeight: 'var(--typography-font-line-height-lh-h1)' }],
        h1: ['var(--typography-font-size-h1)', { lineHeight: 'var(--typography-font-line-height-lh-h1)' }],
        h2: ['var(--typography-font-size-h2)', { lineHeight: 'var(--typography-font-line-height-lh-h2)' }],
        h3: ['var(--typography-font-size-h3)', { lineHeight: 'var(--typography-font-line-height-lh-h3)' }],
        h4: ['var(--typography-font-size-h4)', { lineHeight: 'var(--typography-font-line-height-lh-h4)' }],
        h5: ['var(--typography-font-size-h5)', { lineHeight: 'var(--typography-font-line-height-lh-h5)' }],
        h6: ['var(--typography-font-size-h6)', { lineHeight: 'var(--typography-font-line-height-lh-h6)' }],
        'body-md': ['var(--typography-font-size-body-md)', { lineHeight: 'var(--typography-font-line-height-lh-body-md)' }],
        'body-s': ['var(--typography-font-size-body-s)', { lineHeight: 'var(--typography-font-line-height-lh-body-s)' }],
        'body-xs': ['var(--typography-font-size-body-xs)', { lineHeight: 'var(--typography-font-line-height-lh-body-xs)' }],
        'body-xxs': ['var(--typography-font-size-body-xxs)', { lineHeight: 'var(--typography-font-line-height-lh-body-xxs)' }],
      },
      fontFamily: {
        montserrat: ['var(--typography-font-family-font-family, Montserrat)', 'sans-serif'],
      },
      spacing: {
        'padding-none': 'var(--padding-none)',
        'padding-half': 'var(--padding-half)',
        'padding-xxx-sm': 'var(--padding-xxx-sm)',
        'padding-xx-sm': 'var(--padding-xx-sm)',
        'padding-x-sm': 'var(--padding-x-sm)',
        'padding-sm': 'var(--padding-sm)',
        'padding-md': 'var(--padding-md)',
        'padding-lg': 'var(--padding-lg)',
        'padding-x-lg': 'var(--padding-x-lg)',
        'padding-xx-lg': 'var(--padding-xx-lg)',
        'padding-big': 'var(--padding-big)',
        'margin-none': 'var(--margin-none)',
        'margin-sm': 'var(--margin-sm)',
        'margin-md': 'var(--margin-md)',
        'margin-lg': 'var(--margin-lg)',
        'gap-none': 'var(--gap-none)',
        'gap-x-sm': 'var(--gap-x-sm)',
        'gap-sm': 'var(--gap-sm)',
        'gap-md': 'var(--gap-md)',
        'gap-lg': 'var(--gap-lg)',
      },
      screens: {
        'mobile-sm': '320px',
        'mobile-lg': '767px',
        'tablet-sm': '768px',
        'tablet-lg': '1023px',
        desktop: '1024px',
        'desktop-lg': '1440px',
        'desktop-xl': '1920px',
      },
    },
  },
  plugins: [],
}
