const fs = require('fs');
const path = require('path');

const RAW_DIR = path.resolve('MAPEAR Raw');
const TOKENS_DIR = path.resolve('MAPEAR Tokens');
const COMPONENTS_DIR = path.resolve('MAPEAR Components');
const OUTPUT_CSS = path.resolve('src/styles/design-tokens.css');

function toKebabCase(str) {
  return str
    .replace(/<[^>]+>/g, '') // remove tags like <Forced>
    .replace(/%/g, 'percent') // replace % with percent
    .replace(/[^a-zA-Z0-9\s_-]/g, '') // remove any other non-alphanumeric char
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_.]+/g, '-')
    .replace(/-+/g, '-')
    .toLowerCase();
}

// 1. Process MAPEAR Raw
const rawFilePath = path.join(RAW_DIR, 'font-family.tokens.json');
if (!fs.existsSync(rawFilePath)) {
  console.error('CRITICAL: MAPEAR Raw/font-family.tokens.json not found!');
  process.exit(1);
}

const rawData = JSON.parse(fs.readFileSync(rawFilePath, 'utf-8'));

const rawLookup = {};
const rawCssVars = {};

function processRawNode(obj, pathParts = []) {
  for (const key of Object.keys(obj)) {
    if (key.startsWith('$')) continue;
    const currentParts = [...pathParts, key];
    const val = obj[key];
    if (val && typeof val === 'object') {
      if ('$value' in val) {
        const figmaAliasPath = currentParts.join('/');
        const varName = `--raw-${toKebabCase(currentParts.join('-'))}`;
        let value = val['$value'];
        if (typeof value === 'object' && value.hex) {
          value = value.hex;
        } else if (typeof value === 'number') {
          // add px for numeric values unless opacity or font weight
          const fullName = varName.toLowerCase();
          if (fullName.includes('opacity') || fullName.includes('font-weight') || fullName.includes('line-height') && value < 10) {
            value = value;
          } else {
            value = `${value}px`;
          }
        }
        
        rawLookup[figmaAliasPath] = { varName, value };
        rawCssVars[varName] = value;
      } else {
        processRawNode(val, currentParts);
      }
    }
  }
}

processRawNode(rawData);

// 2. Process MAPEAR Tokens
function processTokenNode(obj, pathParts = []) {
  const cssVars = {};
  
  function walk(currentObj, parts) {
    for (const key of Object.keys(currentObj)) {
      if (key.startsWith('$')) continue;
      const newParts = [...parts, key];
      const val = currentObj[key];
      if (val && typeof val === 'object') {
        if ('$value' in val) {
          const varName = `--${toKebabCase(newParts.join('-'))}`;
          const aliasData = val['$extensions'] && val['$extensions']['com.figma.aliasData'];
          const targetAlias = aliasData ? aliasData.targetVariableName : null;
          
          let cssValue;
          if (targetAlias && rawLookup[targetAlias]) {
            cssValue = `var(${rawLookup[targetAlias].varName})`;
          } else {
            let directVal = val['$value'];
            if (typeof directVal === 'object' && directVal.hex) {
              cssValue = directVal.hex;
            } else if (typeof directVal === 'number') {
              const fullName = varName.toLowerCase();
              if (fullName.includes('weight') || fullName.includes('opacity') || (fullName.includes('line-height') && directVal < 10)) {
                cssValue = directVal;
              } else {
                cssValue = `${directVal}px`;
              }
            } else {
              cssValue = directVal;
            }
          }
          cssVars[varName] = cssValue;
        } else {
          walk(val, newParts);
        }
      }
    }
  }
  
  walk(obj, pathParts);
  return cssVars;
}

const themeConfigs = [
  {
    file: 'FGV Light.tokens.json',
    selectors: [':root', '[data-theme="fgv-light"]', '[data-theme="fgv"][data-color-scheme="light"]'],
    name: 'FGV Light'
  },
  {
    file: 'FGV Dark.tokens.json',
    selectors: ['[data-theme="fgv-dark"]', '[data-theme="fgv"][data-color-scheme="dark"]', '.dark[data-theme="fgv"]'],
    name: 'FGV Dark'
  },
  {
    file: 'CEnPE Light.tokens.json',
    selectors: ['[data-theme="cenpe-light"]', '[data-theme="cenpe"][data-color-scheme="light"]'],
    name: 'CEnPE Light'
  },
  {
    file: 'CEnPE Dark.tokens.json',
    selectors: ['[data-theme="cenpe-dark"]', '[data-theme="cenpe"][data-color-scheme="dark"]', '.dark[data-theme="cenpe"]'],
    name: 'CEnPE Dark'
  }
];

let generatedCss = `/* ==========================================================================
   MAPEAR DESIGN SYSTEM - AUTO GENERATED DESIGN TOKENS
   Do not edit manually. Generated by scripts/build-tokens.cjs
   Architecture: Raw (Primary) -> Tokens (Semantic) -> Components (Devices)
   ========================================================================== */\n\n`;

// Append RAW primitives under :root
generatedCss += `/* --- 1. MAPEAR RAW PRIMITIVES --- */\n:root {\n`;
for (const [varName, value] of Object.entries(rawCssVars)) {
  generatedCss += `  ${varName}: ${value};\n`;
}
generatedCss += `}\n\n`;

// Process Theme files
themeConfigs.forEach(theme => {
  const filePath = path.join(TOKENS_DIR, theme.file);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    const cssVars = processTokenNode(data);
    
    generatedCss += `/* --- MAPEAR THEME: ${theme.name} --- */\n`;
    generatedCss += `${theme.selectors.join(',\n')} {\n`;
    for (const [varName, value] of Object.entries(cssVars)) {
      generatedCss += `  ${varName}: ${value};\n`;
    }
    generatedCss += `}\n\n`;
  }
});

// Generate Accessibility High Contrast Themes
// FGV High Contrast
generatedCss += `/* --- MAPEAR THEME: FGV High Contrast (Accessibility) --- */\n`;
generatedCss += `[data-theme="fgv-high-contrast"], [data-theme="high-contrast"] {\n`;
generatedCss += `  --color-backgrounds-color-bg-layout: #000000;\n`;
generatedCss += `  --color-backgrounds-color-bg-container: #0D0D0D;\n`;
generatedCss += `  --color-text-icon-color-text: #FFFFFF;\n`;
generatedCss += `  --color-text-icon-color-text-heading: #FFFF00;\n`;
generatedCss += `  --color-text-icon-color-text-description: #FFFFFF;\n`;
generatedCss += `  --color-border-color-border: #FFFFFF;\n`;
generatedCss += `  --color-button-solid-primary-color-primary-bg: #FFFF00;\n`;
generatedCss += `  --color-button-solid-primary-color-primary-text-button: #000000;\n`;
generatedCss += `  --color-button-solid-primary-color-primary-bg-hover: #FFFFFF;\n`;
generatedCss += `}\n\n`;

// CEnPE High Contrast
generatedCss += `/* --- MAPEAR THEME: CEnPE High Contrast (Accessibility) --- */\n`;
generatedCss += `[data-theme="cenpe-high-contrast"] {\n`;
generatedCss += `  --color-backgrounds-color-bg-layout: #000000;\n`;
generatedCss += `  --color-backgrounds-color-bg-container: #080C1A;\n`;
generatedCss += `  --color-text-icon-color-text: #FFFFFF;\n`;
generatedCss += `  --color-text-icon-color-text-heading: #00FFFF;\n`;
generatedCss += `  --color-text-icon-color-text-description: #FFFFFF;\n`;
generatedCss += `  --color-border-color-border: #00FFFF;\n`;
generatedCss += `  --color-button-solid-primary-color-primary-bg: #00FFFF;\n`;
generatedCss += `  --color-button-solid-primary-color-primary-text-button: #000000;\n`;
generatedCss += `  --color-button-solid-primary-color-primary-bg-hover: #FFFFFF;\n`;
generatedCss += `}\n\n`;

// 3. Process MAPEAR Components
const componentFiles = [
  { file: 'Desktop.tokens.json', scope: '@media (min-width: 1024px) {\n  :root', name: 'Desktop' },
  { file: 'Tablet.tokens.json', scope: '@media (min-width: 768px) and (max-width: 1023px) {\n  :root', name: 'Tablet' },
  { file: 'Mobile.tokens.json', scope: '@media (max-width: 767px) {\n  :root', name: 'Mobile' }
];

generatedCss += `/* --- 3. MAPEAR COMPONENT METRICS (RESPONSIVE) --- */\n`;
componentFiles.forEach(comp => {
  const filePath = path.join(COMPONENTS_DIR, comp.file);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    const cssVars = processTokenNode(data, ['component']);
    
    generatedCss += `/* Component Metrics: ${comp.name} */\n`;
    generatedCss += `${comp.scope} {\n`;
    for (const [varName, value] of Object.entries(cssVars)) {
      generatedCss += `    ${varName}: ${value};\n`;
    }
    generatedCss += `  }\n}\n\n`;
  }
});

// Write Output
const outputDir = path.dirname(OUTPUT_CSS);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(OUTPUT_CSS, generatedCss, 'utf-8');
console.log(`✅ MAPEAR Design System Tokens compiled successfully to: ${OUTPUT_CSS}`);
